apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-project
  namespace: argocd
spec:
  description: Project for frontend applications

  sourceRepos:
    - https://github.com/Prasadkasralikar/argocd-demos.git

  destinations:
    - namespace: frontend
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
  - name: frontend-admins
    description: Frontend admin access
    policies:
      - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow
    groups:
      - frontend-team
